name: Build kvm_server on arm64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Install dependencies
        run: shards install

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y libogg-dev libopus-dev libasound2-dev libturbojpeg-dev libssl-dev

      - name: Build
        run: crystal build src/main.cr -o kvm_server --release

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: kvm_server-arm64
          path: kvm_server